### ISSUE TITLE
Problem accessing weights file

### ISSUE THREAD

**Issue by lydiagonzalez1** [desti-nation/BlinkFormer#1]
#### Description
I tried downloading the `weights_BlinkFormer_HUST-LEBW_F1_0.843.pth` file from the URL on the repo. However, it seems to be downloading a disk image file.

Is it possible to upload it somewhere else to access it?

Thank you and warm regards.

**Comment by desti-nation** [comment]
Hi,

Apologies for the inconvenience you encountered while attempting to download the weights_BlinkFormer_HUST-LEBW_F1_0.843.pth file. It seems that the file you obtained was a disk image file instead.

To facilitate your access to the weights file, I have uploaded it to a different location. You can now download it from the following link:  https://1drv.ms/u/s!Ao9LJ1mlb4lQlTB-DECODjD0n6HQ?e=DnjjAY 

Please let me know if you encounter any further issues or require any additional assistance.

Warm regards.

**Comment by desti-nation** [comment]
> #### Description
> I tried downloading the `weights_BlinkFormer_HUST-LEBW_F1_0.843.pth` file from the URL on the repo. However, it seems to be downloading a disk image file.
> 
> Is it possible to upload it somewhere else to access it?
> 
> Thank you and warm regards.

Hi,

Apologies for the inconvenience you encountered while attempting to download the weights_BlinkFormer_HUST-LEBW_F1_0.843.pth file. It seems that the file you obtained was a disk image file instead.

To facilitate your access to the weights file, I have uploaded it to a different location. You can now download it from the following link: https://1drv.ms/u/s!Ao9LJ1mlb4lQlTB-DECODjD0n6HQ?e=DnjjAY

Please let me know if you encounter any further issues or require any additional assistance.

Warm regards.

**Comment by lydiagonzalez1** [comment]
Thank you so much. I've downloaded the file now.

Warm regards.
